import { buildEnergyWidgetRenderContext } from './widgetSlotResolvers';

export function buildBasicEnergyWidgetRenderContext(orchestration, runtime) {
  const { widgets, dates } = orchestration;
  const {
    widgetList,
    energyConsumption,
    energySavings,
    peakMinConsumption,
    energyConsumptionLoading,
    energySavingsLoading,
    peakMinConsumptionLoading,
    savingsByStrategy,
    totalConsumptionByGroup,
    lightPowerDensity,
    lightingUnit,
    globalLoading,
    selectedDuration,
    currentDate,
    currentYear,
    selectedAreas,
    areaGroups,
    isLargeScreen,
    chartHeaderStyle,
    ChartLoader,
    transformDataForCharts,
    energyLineChartSurface,
    energyMetricLight,
    consumptionExportControl,
    savingsExportControl,
    totalConsumptionByGroupExportControl,
    consumptionBlankPreview,
    showEnergyStandaloneDurationFilter,
    renderEnergyLineChartEmptyExtras,
    ENERGY_LIGHT_FULL_CARD_HEIGHT_PX,
  } = runtime;

  return buildEnergyWidgetRenderContext({
    variant: 'basic',
    titles: widgets.energyWidgetTitles,
    widgetList,
    getWidgetTitle: widgets.getWidgetTitle,
    data: {
      memoizedEnergyConsumption: widgets.memoizedEnergyConsumption,
      memoizedEnergySavings: widgets.memoizedEnergySavings,
      savingsByStrategy,
      totalConsumptionByGroup,
      lightPowerDensity,
      lightingUnit,
      peakMinConsumption,
    },
    loading: {
      energyConsumptionLoading,
      energySavingsLoading,
      peakMinConsumptionLoading,
    },
    chartLoading: widgets.chartLoading,
    allEnergyChartsReady: widgets.allEnergyChartsReady,
    globalLoading,
    colors: { consumption: widgets.consumptionColors, savings: widgets.savingsColors },
    chartHeaderStyle,
    ChartLoader,
    transformDataForCharts,
    selectedDuration,
    currentDate,
    currentYear,
    selectedAreas,
    energyCustomNeedsDates: dates.energyCustomNeedsDates,
    isLargeScreen,
    areaGroups,
    overrides: {
      consumption: {
        chartSurface: energyLineChartSurface,
        exportControl: consumptionExportControl,
        emptyStateExtras:
          !showEnergyStandaloneDurationFilter ? renderEnergyLineChartEmptyExtras?.() : null,
        blankChartPreview: consumptionBlankPreview,
        energyLightFullCardHeightPx: ENERGY_LIGHT_FULL_CARD_HEIGHT_PX,
      },
      savings: {
        chartSurface: energyLineChartSurface,
        exportControl: savingsExportControl,
        blankChartPreview: consumptionBlankPreview,
        energyLightFullCardHeightPx: ENERGY_LIGHT_FULL_CARD_HEIGHT_PX,
      },
      savings_by_strategy: {
        chartSurface: energyLineChartSurface,
        energyLightFullCardHeightPx: ENERGY_LIGHT_FULL_CARD_HEIGHT_PX,
      },
      total_consumption_by_group: {
        chartSurface: energyLineChartSurface,
        energyLightFullCardHeightPx: ENERGY_LIGHT_FULL_CARD_HEIGHT_PX,
        exportControl: totalConsumptionByGroupExportControl,
      },
      light_power_density: { chartSurface: energyMetricLight ? 'light' : 'dark' },
      peak_and_minimum_consumption: { chartSurface: energyLineChartSurface },
    },
  });
}

export function buildAdvancedEnergyWidgetRenderContext(orchestration, runtime) {
  const { widgets, dates } = orchestration;
  const {
    widgetList,
    energyConsumptionLoading,
    energySavingsLoading,
    peakMinConsumptionLoading,
    savingsByStrategy,
    totalConsumptionByGroup,
    lightPowerDensity,
    lightingUnit,
    globalLoading,
    selectedDuration,
    currentDate,
    currentYear,
    selectedAreas,
    areaGroups,
    isLargeScreen,
    chartHeaderStyle,
    ChartLoader,
    transformDataForCharts,
    metricPanelBorder,
    widgetContextOverrides,
  } = runtime;

  return buildEnergyWidgetRenderContext({
    variant: 'advanced',
    titles: widgets.energyWidgetTitles,
    widgetList,
    getWidgetTitle: widgets.getWidgetTitle,
    data: {
      memoizedEnergyConsumption: widgets.memoizedEnergyConsumption,
      memoizedEnergySavings: widgets.memoizedEnergySavings,
      savingsByStrategy,
      totalConsumptionByGroup,
      lightPowerDensity,
      lightingUnit,
      peakMinConsumption: runtime.peakMinConsumption,
    },
    loading: {
      energyConsumptionLoading,
      energySavingsLoading,
      peakMinConsumptionLoading,
    },
    chartLoading: widgets.chartLoading,
    allEnergyChartsReady: widgets.allEnergyChartsReady,
    globalLoading,
    colors: { consumption: widgets.consumptionColors, savings: widgets.savingsColors },
    chartHeaderStyle,
    ChartLoader,
    transformDataForCharts,
    selectedDuration,
    currentDate,
    currentYear,
    selectedAreas,
    energyCustomNeedsDates: dates.energyCustomNeedsDates,
    isLargeScreen,
    areaGroups,
    metricPanelBorder,
    overrides: widgetContextOverrides || {},
  });
}

export function buildCustomizedEnergyWidgetRenderContext(orchestration, runtime) {
  const { widgets, dates } = orchestration;
  return buildEnergyWidgetRenderContext({
    variant: 'customized',
    titles: widgets.energyWidgetTitles,
    widgetList: runtime.widgetList,
    getWidgetTitle: widgets.getWidgetTitle,
    data: runtime.widgetContextData || {},
    loading: runtime.widgetContextLoading || {},
    chartLoading: widgets.chartLoading,
    allEnergyChartsReady: widgets.allEnergyChartsReady,
    globalLoading: runtime.globalLoading,
    colors: { consumption: widgets.consumptionColors, savings: widgets.savingsColors },
    chartHeaderStyle: runtime.chartHeaderStyle,
    ChartLoader: runtime.ChartLoader,
    transformDataForCharts: runtime.transformDataForCharts,
    selectedDuration: runtime.selectedDuration,
    currentDate: runtime.currentDate,
    currentYear: runtime.currentYear,
    selectedAreas: runtime.selectedAreas,
    energyCustomNeedsDates: dates.energyCustomNeedsDates,
    isLargeScreen: runtime.isLargeScreen,
    areaGroups: runtime.areaGroups,
    areaIdToDisplayName: runtime.areaIdToDisplayName,
    overrides: runtime.widgetContextOverrides || {},
  });
}
